# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Template get from : https://github.com/troian/golang-cross-example
project_name: tstream
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: darwin-amd64
    main: ./cmd/tstream.go
    binary: tstream
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin-arm64
    main: ./cmd/tstream.go
    binary: tstream
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux-amd64
    main: ./cmd/tstream.go
    binary: tstream
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - main: ./cmd/server.go
    id: tserver
    binary: tserver
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}


archives:
  - id: tstream
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
    replacements:
      darwin: MacOS
      linux: Linux
      amd64: x86_64
    name_template: "tstream_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: server
    builds:
      - server
    replacements:
      darwin: MacOS
      linux: Linux
      amd64: x86_64
    name_template: "server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
